### PR TITLE
include thirdparty

### PR DESCRIPTION
**Pull request by masafumi-inoue**
#44

### CODE REVIEW

**Comment by masafumi-inoue** [comment]
- fltk-1.3.3内の空ディレクトリはgitによって保持されなくていいのか？
- fltk-1.3.3/.gitignoreは効いているべき？いないべき？

**Comment by masafumi-inoue** [comment]
### fltk-1.3.3のライセンス
http://www.fltk.org/index.php
FLTK is provided under the terms of the GNU Library Public License, Version 2 with exceptions that allow for static linking.
http://www.fltk.org/doc-1.3/license.html
December 11, 2001
    The FLTK library and included programs are provided under the terms of the GNU Library General Public License (LGPL) with the following exceptions:
    Modifications to the FLTK configure script, config header file, and makefiles by themselves to support a specific platform do not constitute a modified or derivative work.
    The authors do request that such modifications be contributed to the FLTK project - send all contributions through the "Software Trouble Report" on the following page: http://www.fltk.org/str.php
    Widgets that are subclassed from FLTK widgets do not constitute a derivative work.
    Static linking of applications and widgets to the FLTK library does not constitute a derivative work and does not require the author to provide source code for the application or widget, use the shared FLTK libraries, or link their applications or widgets against a user-supplied version of FLTK.
    If you link the application or widget to a modified version of FLTK, then the changes to FLTK must be provided under the terms of the LGPL in sections 1, 2, and 4.
    You do not have to provide a copy of the FLTK license with programs that are linked to the FLTK library, nor do you have to identify the FLTK license in your program or documentation as required by section 6 of the LGPL.
    However, programs must still identify their use of FLTK. The following example statement can be included in user documentation to satisfy this requirement:

and LGPL

**Comment by masafumi-inoue** [comment]
### tiff-4.0.3のライセンス
Opentoonzで同梱されているとおり、特に問題ない、、、と思う

**Comment by masafumi-inoue** [comment]
- GPLはバイナリー(.lib)の配布は、ソースコードの同時（がそれと同等の）配布をする条件で可能としている

**Comment by kogaki** [comment]
FLTKはGPLより緩いので、配布可能ではありそうですね

**Comment by masafumi-inoue** [comment]
そうですね、ここまで考えればいいかなぁ。
基本的には、元のライセンスを変えないで、ソースコード全体を配布する、ということで問題はないと思います、、、

**Comment by masafumi-inoue** [comment]
Modified BSD License
と
New BSD License
は同じものの別名のようですが、
どちらをつかうべきか？

**Comment by masafumi-inoue** [comment]
では、マージ、、、は明日朝やります。

**Pull request merged**
