### PR TITLE
Linux port

### PR DESCRIPTION
**Pull request by stefantalpalaru**
This is a Linux port using SANE instead of TWAIN as the scanner API. It's very likely it will work on other POSIX-compliant systems too, but it was only tested on Linux.

### CODE REVIEW

**Comment by blurymind** [comment]
Very nice. I will give it a try

**Comment by J5lx** [comment]
Is there any reason for leaving the `.h` extension of the FLTK headers lowercase? I have no idea how you even got it compiled that way, since in the FLTK sources (and [every](http://packages.ubuntu.com/xenial/amd64/libfltk1.3-dev/filelist) [single](http://koji.fedoraproject.org/koji/rpminfo?rpmID=7280747#filelist) [distribution](https://www.archlinux.org/packages/extra/x86_64/fltk/files/) [package](http://packages.slackware.com/?r=slackware-current&p=fltk-1.3.3-i586-2.txz&f) I checked) all the extensions are uppercase `.H`. I had to change all occurrences accordingly to make it compile.

**Comment by stefantalpalaru** [comment]
Sorry, I have .h -> .H symlinks on Gentoo. I'll change the files to use the .H versions.

**Comment by masafumi-inoue** [comment]
I am a programmer of GTS.
I could build at Ubuntu16.04 by few modifications.
Thank you for your Pull request.

**Comment by kogaki** [comment]
I confirmed it works in OSX. Thanks @stefantalpalaru for such a great commit! Following is a step to build in OSX.

**Comment by mmuman** [comment]
Cool, I can strike that off my TODO list 🙌

**Pull request merged**
